"""add_saved_to_listings

Revision ID: 92fe7062100a
Revises: 4ed4e0f3987b
Create Date: 2026-06-18 16:26:21.126320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fe7062100a'
down_revision: Union[str, Sequence[str], None] = '4ed4e0f3987b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('saved', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'saved')
    # ### end Alembic commands ###
